# Use postgres/example user/password credentials
version: '3.9'

networks:
  challenge-network:
    name: challenge-network
    driver: bridge

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5498:5432
    networks:
      - challenge-network
    volumes:
      - "$PWD/my-postgres.conf:/etc/postgresql/postgresql.conf"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: 1010
      POSTGRES_DB: testeDB
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: md5

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - challenge-network
    container_name: redis

  api:
    networks:
      - challenge-network
    container_name: api
    build: "./"
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres 
      DB_PASSWORD: 1010
      DB_NAME: testeDB
      DEVELOPMENT: true
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: 156416546548548948948984969441